pipeline {
    agent any
    tools {
        maven "MAVEN3.9"
        jdk "JDK17"
    }

    environment {
        registryCredential = 'nexuslogin'
        nexusDockerRegistry = '192.168.56.201:5000'
        appRegistry = "${nexusDockerRegistry}/vprofileappimg"
    }

    stages {
        stage("Deploy to Prod Docker Engine") {
            steps {
                script {
                    def dockerImage = docker.image("${appRegistry}:latest")

                    docker.withRegistry("http://${nexusDockerRegistry}", registryCredential) {
                        dockerImage.pull()
                    }

                    sh """
                        docker stop vprofileapp_prod || true
                        docker rm vprofileapp_prod || true
                        docker run -d --name vprofileapp_prod -p 8082:8080 ${appRegistry}:latest
                    """
                }
            }
        }
    }
}
