pipeline {
    agent any
    tools {
        maven "MAVEN3.9"
        jdk "JDK17"
    }

    environment {
        SNAP_REPO = 'vprofile-snamshot'
        NEXUS_USER = 'admin'
        NEXUS_PASS = 'rdxx12rd'
        RELEASE_REPO = 'vprofile-release'
        CENTRAL_REPO = 'vpro-maven-central'
        NEXUSIP = '192.168.56.201'
        NEXUSPORT = '8081'
        NEXUS_GRP_REPO = 'vpro-maven-group'
        NEXUS_LOGIN = 'nexuslogin'
        SONARSERVER = 'sonarserver'
        SONARSCANNER = 'sonarscanner'

        registryCredential='nexuslogin'
        nexusDockerRegistry='192.168.56.201:5000'
        appRegistry="${nexusDockerRegistry}/vprofileappimg"
    }

    stages {
         stage('Setup parameters') {
            steps {
                script { 
                    properties([
                        parameters([
                            string(
                                defaultValue: '', 
                                name: 'BUILD', 
                            ),
							string(
                                defaultValue: '', 
                                name: 'TIME', 
                            )
                        ])
                    ])
                }
            }
		}


stage('Ansible Deploy to prod') {
    steps {
        ansiblePlaybook([
            inventory   : 'ansible/stage.inventory',
            playbook    : 'ansible/site.yml',
            installation: 'ansible',
            colorized   : true,
            credentialsId: 'vagrant_insecure_key', 
            disableHostKeyChecking: true,
            extraVars   : [
                USER: "admin",
                PASS: "${NEXUS_PASS}",
                nexusip: "192.168.56.201",
                reponame: "vprofile-release",
                groupid: "QA",
                time: "${env.TIME}",
                build: "${env.BUILD}",
                artifactid: "vproapp",
                vprofile_version: "vproapp-${env.BUILD}-${env.TIME}.war"
            ]
        ])
    }
}

    }
}
