pipeline {
    agent any
    tools {
        maven "MAVEN3.9"
        jdk "JDK17"
    }

    environment {
        SNAP_REPO = 'vprofile-snamshot'
        NEXUS_USER = 'admin'
        NEXUS_PASS = 'rdxx12rd'
        RELEASE_REPO = 'vprofile-release'
        CENTRAL_REPO = 'vpro-maven-central'
        NEXUSIP = '192.168.56.201'
        NEXUSPORT = '8081'
        NEXUS_GRP_REPO = 'vpro-maven-group'
        NEXUS_LOGIN = 'nexuslogin'
        SONARSERVER = 'sonarserver'
        SONARSCANNER = 'sonarscanner'

        registryCredential='nexuslogin'
        nexusDockerRegistry='192.168.56.201:5000'
        appRegistry="${nexusDockerRegistry}/vprofileappimg"
    }

    stages {
        stage('Build') {
            steps {
                sh 'mvn -s settings.xml -DskipTests install'
            }
            post {
                success {
                    echo "Build succeeded"
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }

        stage('Test') {
            steps {
                sh 'mvn -s settings.xml test'
            }
        }

        stage('Check Style Analysis') {
            steps {
                sh 'mvn -s settings.xml checkstyle:checkstyle'
            }
        }

        stage("Sonar Analysis") {
            environment {
                scannerHome = tool "${SONARSCANNER}"
            }
            steps {
                withSonarQubeEnv("${SONARSERVER}") {
                    sh '''${scannerHome}/bin/sonar-scanner -Dsonar.projectKey=vprofile \
                       -Dsonar.projectName=vprofile \
                       -Dsonar.projectVersion=1.0 \
                       -Dsonar.sources=src/ \
                       -Dsonar.java.binaries=target/test-classes/com/visualpathit/account/controllerTest/ \
                       -Dsonar.junit.reportsPath=target/surefire-reports/ \
                       -Dsonar.jacoco.reportsPath=target/jacoco.exec \
                       -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml'''
                }
            }
        }

        stage("Quality Gate") {
            steps {
                timeout(time: 1, unit: 'HOURS') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage("Upload Artifact to Nexus") {
            steps {
                nexusArtifactUploader(
                    nexusVersion: 'nexus3',
                    protocol: 'http',
                    nexusUrl: "${NEXUSIP}:${NEXUSPORT}",
                    groupId: 'QA',
                    version: "${env.BUILD_ID}-${env.BUILD_TIMESTAMP}",
                    repository: "${RELEASE_REPO}",
                    credentialsId: "${NEXUS_LOGIN}",
                    artifacts: [
                        [artifactId: 'vproapp',
                         classifier: '',
                         file: 'target/vprofile-v2.war',
                         type: 'war']
                    ]
                )
            }
        }
        
stage('Ansible Deploy to Staging') {
    steps {
        ansiblePlaybook([
            inventory   : 'ansible/inventory',   // <-- your Vagrant inventory file
            playbook    : 'ansible/deploy-app.yml',
            installation: 'ansible',             // name of Ansible installation in Jenkins
            colorized   : true,
            credentialsId: 'vagrant-ssh',        // Jenkins credentials for Vagrant key
            disableHostKeyChecking: true,
            extraVars   : [
                USER: "admin",
                PASS: "${NEXUS_PASS}",            // Nexus password from Jenkins credential/env
                nexusip: "192.168.56.201",       // Nexus VM IP in your VirtualBox hostonly network
                reponame: "vprofile-release",
                groupid: "QA/vproapp",           // your repo group path
                build: "${env.BUILD_ID}",        // Jenkins build ID
                time: "${env.BUILD_TIMESTAMP}",  // Jenkins timestamp env
                artifactid: "vproapp",
                vprofile_version: "vproapp-${env.BUILD_ID}-${env.BUILD_TIMESTAMP}.war"
            ]
        ])
    }
}



        stage("Build Docker Image") {
            steps {
                script {
                    dockerImage = docker.build("${appRegistry}:${BUILD_NUMBER}", "./Docker-files/app/multistage/")
                }
            }
        }

        stage("Push Docker Image to Nexus") {
            steps {
                script {

                    docker.withRegistry("http://${nexusDockerRegistry}", registryCredential) {
                        dockerImage.push("${BUILD_NUMBER}")
                        dockerImage.push("latest")
                    }
                }
            }
        }

        stage("Deploy to Docker Engine") {
            steps {
                script {
                    def dockerImage = docker.image("${appRegistry}:latest")
                    docker.withRegistry("http://${nexusDockerRegistry}", registryCredential) {
                        dockerImage.pull()
                    }

                    sh """
                        docker stop vprofileapp || true
                        docker rm vprofileapp || true
                        docker run -d --name vprofileapp -p 8081:8080 ${appRegistry}:latest
                    """
                }
            }
        }
    }
}
